FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY w7_feature_engineering ./w7_feature_engineering
COPY w8_weather_prediction_model ./w8_weather_prediction_model
COPY w9_ml_pipeline ./w9_ml_pipeline
COPY w10_fastapi_service ./w10_fastapi_service

WORKDIR /workspace/w10_fastapi_service

EXPOSE 8051

CMD ["python", "-m", "dashboard.app"]