
x-airflow-common: &airflow-common
  build: .
  image: airflow-custom:latest

  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: http://airflow-apiserver:8080/execution/

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    AIRFLOW__API_AUTH__JWT_SECRET: airflow_jwt_secret
    AIRFLOW__API_AUTH__JWT_ISSUER: airflow

    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"

    MINIO_ENDPOINT: http://minio:9000

    W7_FEATURE_DATA_PATH: /opt/airflow/w7/data/processed/w7_features_final.parquet

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - ./data:/opt/airflow/data

    - ../w5_spark_weather_etl:/opt/airflow/w5
    - ../w6_visualisation_dashboard:/opt/airflow/w6
    - ../w7_feature_engineering:/opt/airflow/w7
    - ../w8_weather_prediction_model:/opt/airflow/w8
    - ../w9_ml_pipeline:/opt/airflow/w9

services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD","pg_isready","-U","airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

    restart: always


  minio:
    image: minio/minio

    container_name: minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

    command: server /data --console-address ":9001"

    volumes:
      - minio-data:/data

    restart: always


  airflow-init:

    <<: *airflow-common

    depends_on:
      postgres:
        condition: service_healthy

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db migrate

        airflow users create \
          --username admin \
          --firstname admin \
          --lastname user \
          --role Admin \
          --email admin@email.com \
          --password admin || true

    restart: "no"


  airflow-apiserver:

    <<: *airflow-common

    command: api-server

    ports:
      - "8080:8080"

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    healthcheck:
      test: ["CMD","curl","--fail","http://localhost:8080/api/v2/monitor/health"]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: always


  airflow-scheduler:

    <<: *airflow-common

    command: scheduler

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "airflow jobs check --job-type SchedulerJob --hostname $$HOSTNAME"
        ]

    restart: always

  airflow-dag-processor:

    <<: *airflow-common

    command: dag-processor

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "airflow jobs check --job-type DagProcessorJob --hostname $$HOSTNAME"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

    restart: always


  dashboard:

    build: ../w6_visualisation_dashboard

    container_name: dashboard

    ports:
      - "8050:8050"

    volumes:
      - ../w6_visualisation_dashboard:/opt/airflow/w6
      - ./data:/opt/airflow/data

    environment:
      MINIO_ENDPOINT: http://minio:9000

    depends_on:
      minio:
        condition: service_started

    command: python /opt/airflow/w6/src/app.py

    restart: always


volumes:

  postgres-db-volume:

  minio-data: