apiVersion: apps/v1
kind: Deployment

metadata:
  name: fastapi-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fastapi

  template:
    metadata:
      labels:
        app: fastapi

    spec:
      containers:
        - name: fastapi
          image: data_engineering_portfolio-fastapi:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: PYTHONUNBUFFERED
              value: "1"